[View in Colaboratory](https://colab.research.google.com/github/kbsh/googlecolabsample1/blob/master/keisan.ipynb)

In [0]:
import numpy as np

In [0]:
a = np.array([[2,4],[0,4],[7,9],[3,7]])

In [0]:
b = np.array([[9,2],[4,1],[1,7],[0,2]])

In [19]:
a + b

array([[11,  6],
       [ 4,  5],
       [ 8, 16],
       [ 3,  9]])

In [0]:
c = np.array([[1,3,7],[2,9,0]])

In [21]:
c + b

ValueError: ignored

In [8]:
6 * c

array([[ 6, 18, 42],
       [12, 54,  0]])

In [0]:
d = np.array([[6,3],[0,1]])

In [10]:
d / 3

array([[2, 1],
       [0, 0]])

// 型変換されない？

In [15]:
1 / 3

0

In [0]:
e = np.array([[2],[1],[0],[3]])

In [0]:
f = np.array([[4],[2],[3],[1]])

In [0]:
g = np.array([[6],[0],[3],[12]])

In [14]:
(5*e) - f + (g/6)

array([[ 7],
       [ 3],
       [-3],
       [16]])